//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This ID is already in use. Please choose another one..
        /// </summary>
        internal static string Error_IdExists {
            get {
                return ResourceManager.GetString("Error_IdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid arguments. Use format: 1-3 or 1;3.
        /// </summary>
        internal static string Error_InvalidArgs {
            get {
                return ResourceManager.GetString("Error_InvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice. Please try again..
        /// </summary>
        internal static string Error_InvalidChoice {
            get {
                return ResourceManager.GetString("Error_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ID. Please enter a number between 1 and {0}..
        /// </summary>
        internal static string Error_InvalidId {
            get {
                return ResourceManager.GetString("Error_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid job name. Avoid special characters..
        /// </summary>
        internal static string Error_InvalidName {
            get {
                return ResourceManager.GetString("Error_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path. Please enter a valid directory path..
        /// </summary>
        internal static string Error_InvalidPath {
            get {
                return ResourceManager.GetString("Error_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job not found..
        /// </summary>
        internal static string Error_JobNotFound {
            get {
                return ResourceManager.GetString("Error_JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum number of backup jobs reached ({0})..
        /// </summary>
        internal static string Error_MaxJobs {
            get {
                return ResourceManager.GetString("Error_MaxJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory not found. Please enter an existing path..
        /// </summary>
        internal static string Error_PathNotFound {
            get {
                return ResourceManager.GetString("Error_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- Add Backup Job ---.
        /// </summary>
        internal static string Job_Add_Title {
            get {
                return ResourceManager.GetString("Job_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job added successfully..
        /// </summary>
        internal static string Job_Added {
            get {
                return ResourceManager.GetString("Job_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job deleted successfully..
        /// </summary>
        internal static string Job_Deleted {
            get {
                return ResourceManager.GetString("Job_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done..
        /// </summary>
        internal static string Job_Done {
            get {
                return ResourceManager.GetString("Job_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing job: {0}.
        /// </summary>
        internal static string Job_Executing {
            get {
                return ResourceManager.GetString("Job_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing all backup jobs....
        /// </summary>
        internal static string Job_ExecutingAll {
            get {
                return ResourceManager.GetString("Job_ExecutingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job updated successfully..
        /// </summary>
        internal static string Job_Updated {
            get {
                return ResourceManager.GetString("Job_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup jobs configured..
        /// </summary>
        internal static string Jobs_Empty {
            get {
                return ResourceManager.GetString("Jobs_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- Backup Jobs ---.
        /// </summary>
        internal static string Jobs_List_Title {
            get {
                return ResourceManager.GetString("Jobs_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language changed successfully..
        /// </summary>
        internal static string Language_Changed {
            get {
                return ResourceManager.GetString("Language_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Add a backup job.
        /// </summary>
        internal static string Menu_AddJob {
            get {
                return ResourceManager.GetString("Menu_AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Delete a backup job.
        /// </summary>
        internal static string Menu_DeleteJob {
            get {
                return ResourceManager.GetString("Menu_DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Edit a backup job.
        /// </summary>
        internal static string Menu_EditJob {
            get {
                return ResourceManager.GetString("Menu_EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6. Execute all backup jobs.
        /// </summary>
        internal static string Menu_ExecuteAll {
            get {
                return ResourceManager.GetString("Menu_ExecuteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Execute a backup job.
        /// </summary>
        internal static string Menu_ExecuteJob {
            get {
                return ResourceManager.GetString("Menu_ExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7. Change language.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. List backup jobs.
        /// </summary>
        internal static string Menu_ListJobs {
            get {
                return ResourceManager.GetString("Menu_ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8. Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à === EasySave v1.0 ===.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your choice: .
        /// </summary>
        internal static string Prompt_Choice {
            get {
                return ResourceManager.GetString("Prompt_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue....
        /// </summary>
        internal static string Prompt_Continue {
            get {
                return ResourceManager.GetString("Prompt_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job ID: .
        /// </summary>
        internal static string Prompt_JobId {
            get {
                return ResourceManager.GetString("Prompt_JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job ID (1-{0}): .
        /// </summary>
        internal static string Prompt_JobIdNew {
            get {
                return ResourceManager.GetString("Prompt_JobIdNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name: .
        /// </summary>
        internal static string Prompt_Name {
            get {
                return ResourceManager.GetString("Prompt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source path: .
        /// </summary>
        internal static string Prompt_Source {
            get {
                return ResourceManager.GetString("Prompt_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target path: .
        /// </summary>
        internal static string Prompt_Target {
            get {
                return ResourceManager.GetString("Prompt_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup.
        /// </summary>
        internal static string Type_Differential {
            get {
                return ResourceManager.GetString("Type_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup.
        /// </summary>
        internal static string Type_Full {
            get {
                return ResourceManager.GetString("Type_Full", resourceCulture);
            }
        }
    }
}
